<?php
/** Approved V3 layout, edited through Ma boutique. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$view = belmains_storefront_view();
$product = $view['product'];
$can_buy = ! $view['preview'] && $product && $product->is_purchasable() && $product->is_in_stock();
$offer = belmains_display_offers();
$brand = belmains_value( 'brand_name', 'Belmains' );
$logo = belmains_value( 'brand_logo', array( 'url' => get_theme_file_uri( 'assets/belmains-logo.png' ), 'alt' => $brand ) );
$cart_url = function_exists( 'wc_get_cart_url' ) ? wc_get_cart_url() : home_url( '/#fiche-produit' );
$name = belmains_value( 'product_name', $product ? $product->get_name() : 'Produit' );
$editorials = belmains_value( 'story_enabled' ) ? belmains_value( 'editorials', array() ) : array();
$original_order = 'original' === belmains_value( 'layout_order', 'original' );
?>
<a class="skip-link" href="#main">Aller au contenu</a>
<?php if ( $view['preview'] ) : ?><aside class="belmains-preview-banner" role="status"><strong>Aperçu privé du brouillon</strong> · Les visiteurs voient toujours la version publiée. Les achats sont désactivés ici. <a href="<?php echo esc_url( admin_url( 'admin.php?page=belmains-builder' ) ); ?>">Revenir à l’éditeur</a></aside><?php endif; ?>
<div id="shopify-section-menu_kooldogy_jpEgq8" class="theme-section">
 <header class="kd-menu-menu_kooldogy_jpEgq8" data-kd-menu><div class="kd-menu-inner-menu_kooldogy_jpEgq8">
 <button class="kd-menu-burger-menu_kooldogy_jpEgq8" data-kd-burger aria-label="Menu" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button>
 <ul class="kd-menu-nav-menu_kooldogy_jpEgq8"><li class="kd-menu-item-menu_kooldogy_jpEgq8"><a href="#accueil" class="kd-menu-link-menu_kooldogy_jpEgq8 is-active">Accueil</a></li><li class="kd-menu-item-menu_kooldogy_jpEgq8"><a href="<?php echo esc_url( belmains_contact_url() ); ?>" class="kd-menu-link-menu_kooldogy_jpEgq8">Contact</a></li><?php if ( ! belmains_catalog_only() ) : ?><li class="kd-menu-item-menu_kooldogy_jpEgq8"><a href="<?php echo esc_url( belmains_tracking_url() ); ?>" class="kd-menu-link-menu_kooldogy_jpEgq8">Suivre ma commande</a></li><?php endif; ?></ul>
 <a href="#accueil" class="kd-menu-logo-menu_kooldogy_jpEgq8" aria-label="<?php echo esc_attr( $brand ); ?>"><?php if ( belmains_media_url( $logo ) ) { belmains_image( $logo, '', true ); } else { echo esc_html( $brand ); } ?></a><div class="kd-menu-actions-menu_kooldogy_jpEgq8"><?php if ( ! belmains_catalog_only() ) : ?><a href="<?php echo esc_url( $cart_url ); ?>" class="kd-menu-icon-menu_kooldogy_jpEgq8" aria-label="Voir le panier"><?php belmains_icon( 'bag' ); ?></a><?php endif; ?></div>
 </div></header>
 <div class="kd-drawer-overlay-menu_kooldogy_jpEgq8" data-kd-overlay></div>
 <div class="kd-drawer-menu_kooldogy_jpEgq8" data-kd-drawer aria-hidden="true"><button class="kd-drawer-close-menu_kooldogy_jpEgq8" data-kd-close aria-label="Fermer">×</button><div class="kd-drawer-logo-wrap-menu_kooldogy_jpEgq8"><a href="#accueil" class="kd-drawer-logo-menu_kooldogy_jpEgq8"><?php if ( belmains_media_url( $logo ) ) { belmains_image( $logo ); } else { echo esc_html( $brand ); } ?></a></div><ul class="kd-drawer-nav-menu_kooldogy_jpEgq8"><li><a href="#accueil" class="kd-drawer-link-menu_kooldogy_jpEgq8">Accueil</a></li><li><a href="<?php echo esc_url( belmains_contact_url() ); ?>" class="kd-drawer-link-menu_kooldogy_jpEgq8">Contact</a></li><?php if ( ! belmains_catalog_only() ) : ?><li><a href="<?php echo esc_url( belmains_tracking_url() ); ?>" class="kd-drawer-link-menu_kooldogy_jpEgq8">Suivre ma commande</a></li><?php endif; ?></ul></div>
</div>
<?php if ( belmains_value( 'announcement' ) ) : ?><div class="announcement announcement-red"><p><?php echo esc_html( belmains_value( 'announcement' ) ); ?></p></div><?php endif; ?>
<main id="main">
<?php if ( belmains_value( 'hero_enabled' ) ) : ?>
<div id="shopify-section-hero_custom_TjqNkF" class="theme-section"><section class="hero-editorial"><div class="hero-ed-inner<?php echo belmains_media_url( belmains_value( 'hero_image' ) ) ? '' : ' belmains-text-only'; ?>"><div class="hero-ed-left"><div class="top-badge"><span class="eyebrow-dash"></span><?php echo esc_html( belmains_value( 'hero_eyebrow' ) ); ?></div><h1 class="hero-ed-title"><?php echo belmains_rich( belmains_value( 'hero_title' ) ); ?></h1><?php if ( belmains_value( 'hero_button' ) ) : ?><div class="hero-ed-cta"><a href="#fiche-produit" class="btn btn-primary"><?php echo esc_html( belmains_value( 'hero_button' ) ); ?></a></div><?php endif; ?><?php if ( belmains_value( 'hero_proof' ) ) : ?><div class="hero-ed-proof"><div class="proof-text"><div class="proof-label"><?php echo esc_html( belmains_value( 'hero_proof' ) ); ?></div></div></div><?php endif; ?></div>
<?php if ( belmains_media_url( belmains_value( 'hero_image' ) ) ) : ?><div class="hero-ed-right"><div class="single-image-wrapper"><div class="hero-image"><?php belmains_image( belmains_value( 'hero_image' ), '', true ); ?></div><?php if ( belmains_value( 'hero_badge_text' ) ) : ?><div class="floating-badge"><div class="floating-badge-icon"><?php belmains_icon( 'sun' ); ?></div><div><div class="floating-badge-label"><?php echo esc_html( belmains_value( 'hero_badge_label' ) ); ?></div><div class="floating-badge-title"><?php echo esc_html( belmains_value( 'hero_badge_text' ) ); ?></div></div></div><?php endif; ?></div></div><?php endif; ?></div></section></div>
<?php endif; ?>
<?php if ( $editorials && $original_order ) { belmains_heading( belmains_value( 'intro_heading' ), 'kEE36c' ); belmains_editorial( $editorials[0], 0 ); } ?>
<?php if ( belmains_value( 'brand_ribbon_enabled' ) && belmains_value( 'brand_ribbon' ) ) : ?><div id="shopify-section-brands_mWCJBf" class="theme-section"><div class="section-brands_mWCJBf-padding"><div class="text-marquee-brands_mWCJBf" role="region" aria-label="<?php echo esc_attr( belmains_value( 'brand_ribbon' ) ); ?>"><div class="text-marquee-brands_mWCJBf__track" aria-hidden="true"><?php for ( $group = 0; $group < 2; $group++ ) : ?><div><?php for ( $item = 0; $item < 6; $item++ ) : ?><p class="text-marquee-brands_mWCJBf__item"><?php echo esc_html( belmains_value( 'brand_ribbon' ) ); ?><span class="text-marquee-brands_mWCJBf__separator">●</span></p><?php endfor; ?></div><?php endfor; ?></div></div></div></div><?php endif; ?>
<?php get_template_part( 'template-parts/product', null, array( 'view' => $view, 'product' => $product, 'can_buy' => $can_buy, 'offer' => $offer, 'name' => $name, 'cart_url' => $cart_url ) ); ?>
<?php if ( belmains_value( 'story_enabled' ) ) { if ( $original_order ) { belmains_heading( belmains_value( 'middle_heading' ), 'PkAFHE' ); } else { belmains_heading( belmains_value( 'intro_heading' ), 'kEE36c' ); } foreach ( $editorials as $index => $editorial ) { if ( $original_order && 0 === $index ) { continue; } if ( ! $original_order && 1 === $index ) { belmains_heading( belmains_value( 'middle_heading' ), 'PkAFHE' ); } belmains_editorial( $editorial, $index ); } belmains_heading( belmains_value( 'closing_heading' ), 'PqrYaB' ); } ?>
<?php if ( belmains_value( 'promises_enabled' ) && belmains_value( 'promises', array() ) ) : ?><div id="shopify-section-promess_8CcEiE" class="theme-section"><section class="promesses"><div class="promesses-header"><div class="eyebrow"><span class="eyebrow-dash"></span><?php echo esc_html( belmains_value( 'promises_eyebrow' ) ); ?></div><h2 class="promesses-title"><?php echo belmains_rich( belmains_value( 'promises_title' ) ); ?></h2></div><div class="promesses-grid"><?php foreach ( belmains_value( 'promises', array() ) as $index => $promise ) : ?><div class="promesse-card"><div class="icon-wrap"><?php belmains_icon( array( 'sun', 'heart', 'truck' )[ $index % 3 ] ); ?></div><h3><?php echo esc_html( $promise['title'] ); ?></h3><p><?php echo esc_html( $promise['text'] ); ?></p></div><?php endforeach; ?></div></section></div><?php endif; ?>
<?php if ( belmains_value( 'reviews_enabled' ) && belmains_value( 'reviews', array() ) ) : ?>
<div id="shopify-section-testimonial_custom_JztQEh" class="theme-section"><section id="avis" aria-label="Vos avis" class="kd-testimonials-testimonial_custom_JztQEh"><div class="kd-testimonials-inner-testimonial_custom_JztQEh"><div class="kd-testimonials-header-testimonial_custom_JztQEh"><div class="kd-testimonials-eyebrow-testimonial_custom_JztQEh"><span class="kd-testimonials-eyebrow-dash-testimonial_custom_JztQEh"></span>Vos avis</div><h2 class="kd-testimonials-title-testimonial_custom_JztQEh"><?php echo belmains_rich( belmains_value( 'reviews_title' ) ); ?></h2><?php if ( 'demo' === belmains_value( 'reviews_kind', 'demo' ) ) : ?><p class="belmains-reviews-note">Témoignages de démonstration pour la maquette.</p><?php endif; ?></div><div class="kd-testimonials-carousel-testimonial_custom_JztQEh" data-kd-carousel><div class="kd-testimonials-track-testimonial_custom_JztQEh" data-kd-track>
<?php foreach ( belmains_value( 'reviews', array() ) as $review ) : $rating = max( 1, min( 5, (int) $review['rating'] ) ); ?><article class="kd-testimonial-card-testimonial_custom_JztQEh"><div class="kd-testimonial-stars-testimonial_custom_JztQEh" role="img" aria-label="<?php echo esc_attr( $rating . ' étoiles sur 5' ); ?>"><?php for ( $star = 1; $star <= 5; $star++ ) : ?><svg viewBox="0 0 24 24" aria-hidden="true" fill="<?php echo $star <= $rating ? 'currentColor' : 'none'; ?>" stroke="currentColor"><path d="M12 17.27 18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/></svg><?php endfor; ?></div><blockquote class="kd-testimonial-quote-testimonial_custom_JztQEh"><?php echo esc_html( $review['text'] ); ?></blockquote><div class="kd-testimonial-author-testimonial_custom_JztQEh"><div class="kd-testimonial-photo-placeholder-testimonial_custom_JztQEh" aria-hidden="true"><?php echo esc_html( function_exists( 'mb_substr' ) ? mb_substr( $review['name'], 0, 1 ) : substr( $review['name'], 0, 1 ) ); ?></div><div class="kd-testimonial-meta-testimonial_custom_JztQEh"><div class="kd-testimonial-name-testimonial_custom_JztQEh"><?php echo esc_html( $review['name'] ); ?></div></div></div></article><?php endforeach; ?>
</div><?php if ( count( belmains_value( 'reviews', array() ) ) > 1 ) : ?><button class="kd-testimonials-nav-testimonial_custom_JztQEh kd-testimonials-prev-testimonial_custom_JztQEh" data-kd-prev aria-label="Témoignage précédent">←</button><button class="kd-testimonials-nav-testimonial_custom_JztQEh kd-testimonials-next-testimonial_custom_JztQEh" data-kd-next aria-label="Témoignage suivant">→</button><div class="kd-testimonials-dots-testimonial_custom_JztQEh" data-kd-dots><?php foreach ( belmains_value( 'reviews', array() ) as $index => $review ) : ?><button class="kd-testimonials-dot-testimonial_custom_JztQEh<?php echo 0 === $index ? ' is-active' : ''; ?>" data-kd-dot="<?php echo esc_attr( $index ); ?>" aria-label="<?php echo esc_attr( 'Aller au témoignage ' . ( $index + 1 ) ); ?>"></button><?php endforeach; ?></div><?php endif; ?></div></div></section></div><?php endif; ?>
<?php $slides = array_values( array_filter( belmains_value( 'slides', array() ), static function ( $slide ) { return belmains_media_url( $slide['image'] ?? array() ); } ) ); if ( belmains_value( 'slideshow_enabled' ) && $slides ) : ?>
<div id="shopify-section-diaporama_belmains" class="theme-section"><div id="Diapo-diaporama_belmains" class="diapo" data-diapo><div class="diapo__cadre"><div class="diapo__piste" role="region" aria-roledescription="carrousel" aria-label="<?php echo esc_attr( 'Découvrez ' . $brand ); ?>">
<?php foreach ( $slides as $index => $slide ) : ?><article class="diapo__slide diapo__slide--left<?php echo 0 === $index ? ' is-active' : ''; ?>" role="group" aria-roledescription="diapositive" aria-label="<?php echo esc_attr( ( $index + 1 ) . ' / ' . count( $slides ) ); ?>" aria-hidden="<?php echo 0 === $index ? 'false' : 'true'; ?>"><div class="diapo__media"><?php belmains_image( $slide['image'] ); ?><div class="diapo__voile" aria-hidden="true"></div></div><div class="diapo__contenu"><p class="diapo__surtitre"><?php echo esc_html( $slide['eyebrow'] ); ?></p><h2 class="diapo__titre"><?php echo belmains_rich( $slide['title'] ); ?></h2><?php if ( $slide['text'] ) : ?><div class="diapo__texte"><?php echo belmains_paragraphs( $slide['text'] ); ?></div><?php endif; ?><?php if ( $slide['button'] ) : ?><a class="diapo__bouton" href="#fiche-produit"><?php echo esc_html( $slide['button'] ); ?></a><?php endif; ?></div></article><?php endforeach; ?>
<?php if ( count( $slides ) > 1 ) : ?><button class="diapo__fleche diapo__fleche--prev" type="button" data-prev aria-label="Diapositive précédente"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5l-7 7 7 7" fill="none" stroke="currentColor" stroke-width="2"/></svg></button><button class="diapo__fleche diapo__fleche--next" type="button" data-next aria-label="Diapositive suivante"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5l7 7-7 7" fill="none" stroke="currentColor" stroke-width="2"/></svg></button><?php endif; ?></div>
<?php if ( count( $slides ) > 1 ) : ?><div class="diapo__nav"><div class="diapo__points" role="tablist"><?php foreach ( $slides as $index => $slide ) : ?><button type="button" role="tab" data-goto="<?php echo esc_attr( $index ); ?>" aria-label="<?php echo esc_attr( 'Charger la diapositive ' . ( $index + 1 ) ); ?>" aria-selected="<?php echo 0 === $index ? 'true' : 'false'; ?>"<?php echo 0 === $index ? ' class="is-active"' : ''; ?>></button><?php endforeach; ?></div><button type="button" class="diapo__pause" data-pause aria-label="Mettre le diaporama en pause"><span class="ic-pause" aria-hidden="true">Ⅱ</span><span class="ic-play" aria-hidden="true">▶</span></button></div><?php endif; ?></div></div></div><?php endif; ?>
<?php if ( belmains_value( 'faq_enabled' ) && belmains_value( 'faq', array() ) ) : ?><div id="shopify-section-faq_3knxkP" class="theme-section"><section class="faq-section" id="faq"><div class="faq-inner"><div class="section-header"><div class="eyebrow"><span class="eyebrow-dash"></span>Questions fréquentes</div><h2 class="section-title"><?php echo belmains_rich( belmains_value( 'faq_title' ) ); ?></h2><p class="section-subtitle"><?php echo esc_html( belmains_value( 'faq_intro' ) ); ?></p></div><div class="faq-list"><?php foreach ( belmains_value( 'faq', array() ) as $index => $faq ) : ?><div class="faq-item<?php echo 0 === $index ? ' open' : ''; ?>"><button class="faq-trigger" type="button" aria-expanded="<?php echo 0 === $index ? 'true' : 'false'; ?>"><?php echo esc_html( $faq['question'] ); ?><span class="plus">+</span></button><div class="faq-body"><p><?php echo nl2br( esc_html( $faq['answer'] ) ); ?></p></div></div><?php endforeach; ?></div></div></section></div><?php endif; ?>
</main>
<div id="shopify-section-waves_ptbQNq" class="theme-section"><div class="section-waves_ptbQNq-padding" style="position:relative"><div class="ocean-waves_ptbQNq"><div class="wave"></div><div class="wave"></div><div class="wave"></div></div></div></div>
<footer class="mock-footer" id="contact"><div class="footer-grid"><a href="#accueil" class="footer-logo"><?php if ( belmains_media_url( $logo ) ) { belmains_image( $logo ); } else { echo esc_html( $brand ); } ?></a><div><h2>Liens rapides</h2><?php if ( belmains_value( 'faq_enabled' ) && belmains_value( 'faq', array() ) ) : ?><a href="#faq">Questions fréquentes</a><?php endif; ?><button data-info="delivery">Livraison et retours</button><?php if ( belmains_legal_url( 'legal' ) ) : ?><a href="<?php echo esc_url( belmains_legal_url( 'legal' ) ); ?>">Mentions légales</a><?php else : ?><button data-info="legal">Mentions légales</button><?php endif; ?><?php foreach ( array( 'terms' => 'Conditions de vente', 'privacy' => 'Confidentialité', 'returns' => 'Retours' ) as $kind => $label ) { if ( belmains_legal_url( $kind ) ) { echo '<a href="' . esc_url( belmains_legal_url( $kind ) ) . '">' . esc_html( $label ) . '</a>'; } } ?></div><div><h2>Boutique</h2><a href="#accueil">Accueil</a><a href="#fiche-produit"><?php echo esc_html( belmains_value( 'footer_product_label', $name ) ); ?></a><?php if ( ! belmains_catalog_only() ) : ?><a href="<?php echo esc_url( belmains_tracking_url() ); ?>">Suivre ma commande</a><?php endif; ?></div><div><h2>Contact</h2><?php echo belmains_paragraphs( belmains_value( 'footer_text' ) ); ?><a class="contact-button" href="<?php echo esc_url( belmains_contact_url() ); ?>">Nous contacter ↗</a></div></div><div class="footer-bottom"><span><?php echo esc_html( function_exists( 'get_woocommerce_currency' ) ? get_woocommerce_currency() : 'EUR' ); ?> · Français</span><p>© <?php echo esc_html( wp_date( 'Y' ) . ' ' . $brand ); ?></p></div><p class="footer-credit"><?php echo esc_html( belmains_value( 'footer_credit' ) ); ?></p><div class="prototype-tools"><?php if ( belmains_value( 'reviews_enabled' ) && 'demo' === belmains_value( 'reviews_kind', 'demo' ) ) : ?><span>Maquette de présentation · Avis de démonstration</span><?php endif; ?><button id="motion-toggle" aria-pressed="false">Mettre les animations en pause</button></div></footer>
<dialog class="info-dialog" id="info-dialog" aria-labelledby="info-title"><div class="dialog-top"><h2 id="info-title"></h2><button data-close aria-label="Fermer">×</button></div><div id="info-content"></div></dialog>
<?php foreach ( array( 'sizes' => array( belmains_value( 'size_guide_title' ), belmains_value( 'size_guide_text' ) ), 'delivery' => array( 'Livraison et retours', belmains_value( 'delivery_text' ) ), 'legal' => array( 'Mentions légales', belmains_value( 'legal_text' ) ) ) as $key => $content ) : ?><template data-info-content="<?php echo esc_attr( $key ); ?>" data-title="<?php echo esc_attr( $content[0] ); ?>"><?php echo belmains_paragraphs( $content[1] ); ?></template><?php endforeach; ?>
<dialog id="gallery-dialog" class="gallery-dialog" aria-labelledby="gallery-dialog-title"><div class="dialog-top"><h2 id="gallery-dialog-title"><?php echo esc_html( $name . ' en détail' ); ?></h2><button data-close aria-label="Fermer l’image agrandie">×</button></div><p id="gallery-dialog-caption"></p><div class="gallery-zoom-scroll"><button id="gallery-zoom-toggle" type="button" aria-label="Zoomer sur l’image"><img id="gallery-dialog-image" alt=""></button></div><p class="gallery-zoom-hint">Touchez l’image pour zoomer.</p></dialog>
