<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
extract( $args, EXTR_SKIP );
$gallery = array();
$product_heading = belmains_value( 'hero_enabled' ) && trim( wp_strip_all_tags( belmains_value( 'hero_title' ) ) ) ? 'h2' : 'h1';
$video = belmains_value( 'product_video', array() );
$poster = belmains_value( 'video_poster', array() );
if ( belmains_media_url( $video ) ) { $gallery[] = array( 'type' => 'video', 'media' => $video, 'thumb' => $poster, 'label' => belmains_value( 'video_label', 'Vidéo du produit' ) ); }
foreach ( belmains_value( 'gallery', array() ) as $image ) { if ( belmains_media_url( $image['image'] ?? array() ) ) { $gallery[] = array( 'type' => 'image', 'media' => $image['image'], 'thumb' => $image['image'], 'label' => $image['label'] ); } }
?>
<section id="fiche-produit" class="mock-product" aria-labelledby="product-title"><div class="mock-product-grid<?php echo $gallery ? '' : ' belmains-text-only'; ?>">
<?php if ( $gallery ) : ?><div class="product-gallery"><div class="product-stage" tabindex="0" aria-label="Galerie du produit. Flèches gauche et droite pour changer de vue.">
<?php foreach ( $gallery as $index => $item ) : if ( 'video' === $item['type'] ) : ?><video id="product-film" class="product-view product-film<?php echo 0 === $index ? ' is-active' : ''; ?>" src="<?php echo esc_url( belmains_media_url( $video ) ); ?>"<?php echo belmains_media_url( $poster ) ? ' poster="' . esc_url( belmains_media_url( $poster ) ) . '"' : ''; ?> aria-label="<?php echo esc_attr( $item['label'] ); ?>" data-label="<?php echo esc_attr( $item['label'] ); ?>" width="1280" height="720" loop muted playsinline controls preload="none"<?php echo 0 === $index ? '' : ' hidden'; ?>></video><?php else : ?><img class="product-view product-marketing<?php echo 0 === $index ? ' is-active' : ''; ?>" src="<?php echo esc_url( belmains_media_url( $item['media'] ) ); ?>" alt="<?php echo esc_attr( $item['media']['alt'] ?? $item['label'] ); ?>" data-label="<?php echo esc_attr( $item['label'] ); ?>" loading="<?php echo 0 === $index ? 'eager' : 'lazy'; ?>" decoding="async"<?php echo 0 === $index ? '' : ' hidden'; ?>><?php endif; endforeach; ?>
<?php if ( count( $gallery ) > 1 ) : ?><button data-gallery-prev aria-label="Photo précédente">←</button><button data-gallery-next aria-label="Photo suivante">→</button><?php endif; ?></div>
<?php if ( belmains_media_url( $video ) ) : ?><button id="product-film-toggle" class="product-film-toggle" type="button" aria-label="Lire la vidéo du produit" hidden><span aria-hidden="true" class="product-film-icon">▶</span><span class="product-film-state">Lire</span></button><?php endif; ?><button id="gallery-expand" class="gallery-expand" type="button" hidden>Agrandir l’image ↗</button>
<?php if ( count( $gallery ) > 1 ) : ?><div class="product-thumbs"><?php foreach ( $gallery as $index => $item ) : ?><button data-gallery="<?php echo esc_attr( $index ); ?>" aria-label="<?php echo esc_attr( $item['label'] ?: 'Vue ' . ( $index + 1 ) ); ?>" aria-pressed="<?php echo 0 === $index ? 'true' : 'false'; ?>"><?php if ( belmains_media_url( $item['thumb'] ) ) { belmains_image( array_merge( $item['thumb'], array( 'alt' => '' ) ), '', false, true ); } else { echo '<span aria-hidden="true">▶</span>'; } ?></button><?php endforeach; ?></div><?php endif; ?><p class="gallery-label" aria-live="polite"><?php echo esc_html( '1 / ' . count( $gallery ) . ' · ' . $gallery[0]['label'] ); ?></p></div><?php endif; ?>
<div class="product-information"><<?php echo $product_heading; ?> id="product-title"><?php echo esc_html( $name ); ?></<?php echo $product_heading; ?>><p class="product-kicker"><?php echo esc_html( belmains_value( 'product_kicker' ) ); ?></p>
<p class="product-price" aria-live="polite"><span id="product-price-label">1 produit</span> <strong id="product-price"><?php echo belmains_price( $offer['single_cents'] ); ?></strong> <span id="product-compare-label" class="visually-hidden"<?php echo $offer['regular_cents'] > $offer['single_cents'] ? '' : ' hidden'; ?>>au lieu de</span> <del id="product-compare-price"<?php echo $offer['regular_cents'] > $offer['single_cents'] ? '' : ' hidden'; ?>><?php echo belmains_price( $offer['regular_cents'] ); ?></del></p>
<p class="product-description"><?php echo nl2br( esc_html( belmains_value( 'product_description' ) ) ); ?></p>
<?php if ( belmains_value( 'benefits', array() ) ) : ?><ul class="comfort-benefits"><?php foreach ( belmains_value( 'benefits', array() ) as $benefit ) : ?><li><span><?php belmains_icon(); ?></span><?php echo esc_html( $benefit['text'] ); ?></li><?php endforeach; ?></ul><?php endif; ?>
<noscript><style>.product-offers,[data-qty]{display:none!important}</style><p>Saisissez la quantité souhaitée. Les offres sont appliquées automatiquement dans le panier.</p></noscript>
<?php if ( $offer['duo_enabled'] ) : ?><fieldset class="product-offers"><legend>Choisissez votre offre</legend><?php foreach ( array( array( 1, $offer['single_cents'], $offer['regular_cents'] ), array( 2, $offer['duo_cents'], $offer['duo_regular_cents'] ) ) as $choice ) : ?><label class="product-offer"><input type="radio" name="product-offer" value="<?php echo esc_attr( $choice[0] ); ?>"<?php checked( 1, $choice[0] ); ?>><span><b><?php echo esc_html( $choice[0] . ( 1 === $choice[0] ? ' produit' : ' produits' ) ); ?></b><span class="offer-prices"><strong><?php echo belmains_price( $choice[1] ); ?></strong><?php if ( $choice[2] > $choice[1] ) : ?><span class="visually-hidden">au lieu de</span><del><?php echo belmains_price( $choice[2] ); ?></del><?php endif; ?></span></span></label><?php endforeach; ?></fieldset><?php endif; ?>
<div class="quantity-row"><label for="product-quantity">Quantité</label><div class="quantity"><button type="button" data-qty="minus" aria-label="Diminuer la quantité">−</button><input name="quantity" form="belmains-product-form" id="product-quantity" type="number" value="1" min="1" max="<?php echo esc_attr( class_exists( 'Belmains_Commerce' ) ? Belmains_Commerce::MAX_QUANTITY : 999 ); ?>" inputmode="numeric"><button type="button" data-qty="plus" aria-label="Augmenter la quantité">+</button></div></div>
<?php if ( belmains_value( 'color' ) ) : ?><p class="product-finish"><span></span><?php echo esc_html( belmains_value( 'color' ) ); ?></p><?php endif; ?>
<?php if ( belmains_value( 'reassurance', array() ) ) : ?><div class="reassurance-list"><?php foreach ( belmains_value( 'reassurance', array() ) as $index => $line ) : ?><div><?php belmains_icon( 0 === $index ? 'truck' : 'check' ); ?><p><strong><?php echo esc_html( $line['title'] ); ?></strong><span><?php echo esc_html( $line['text'] ); ?></span></p></div><?php endforeach; ?></div><?php endif; ?>
<?php if ( belmains_value( 'product_details', array() ) ) : ?><div class="product-accordions"><?php foreach ( belmains_value( 'product_details', array() ) as $detail ) : ?><details><summary><?php belmains_icon( 'heart' ); ?><?php echo esc_html( $detail['title'] ); ?><span>+</span></summary><div><?php echo belmains_paragraphs( $detail['text'] ); ?></div></details><?php endforeach; ?></div><?php endif; ?>
<?php if ( belmains_value( 'size_guide_title' ) ) : ?><button class="size-guide" data-info="sizes"><?php echo esc_html( belmains_value( 'size_guide_title' ) ); ?></button><?php endif; ?>
<form id="belmains-product-form" action="<?php echo esc_url( $cart_url ); ?>" method="post"><?php if ( $product && ! $view['preview'] ) : ?><input type="hidden" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>"><?php endif; ?><button class="add-to-cart" id="add-to-cart" type="submit" <?php disabled( ! $can_buy ); ?>><?php echo $view['preview'] ? 'Aperçu — achat désactivé' : ( $can_buy ? 'Ajouter au panier' : 'Actuellement indisponible' ); ?> <span aria-hidden="true">→</span></button><p id="purchase-feedback" class="purchase-feedback" tabindex="-1" role="status" hidden></p></form><p class="purchase-note">Les offres sont appliquées automatiquement dans votre panier.</p>
</div></div></section>
